# Copyright 2020, akashche at redhat.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: cpp

sudo: required

services:
  - docker

os:
  - linux

env:
  global:
    - OJDK_MILESTONE=ojdkbuild
    - OJDK_WITH_NATIVE_DEBUG_SYMBOLS=none
    - OJDK_WITH_DEBUG_LEVEL=release

before_install:
  - set -e
  - export OJDK_TAG=`git describe --exact-match --tags HEAD`
  - if [ -z ${OJDK_TAG} ] ; then exit 1 ; fi
  - echo ${OJDK_TAG}
  - export OJDK_UPDATE=`echo ${OJDK_TAG} | sed 's/\./ /g' | sed 's/+/ /' | awk '{print $3}'`
  - echo ${OJDK_UPDATE}
  - export OJDK_BUILD=`echo ${OJDK_TAG} | sed 's/+/ /' | awk '{print $2}'`
  - echo ${OJDK_BUILD}
  - export OJDK_IMAGE=jdk-15.0.${OJDK_UPDATE}-${OJDK_MILESTONE}-linux-x64
  - export D="docker exec builder"
  - docker pull centos:6
  - docker run
            -id
            --name builder
            -w /opt
            -v `pwd`:/host
            -e LD_LIBRARY_PATH=/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/autotools-latest/root/usr/lib64
            -e PATH=/opt/rh/devtoolset-7/root/usr/bin:/opt/rh/autotools-latest/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            centos:6 bash

install:
  - $D yum update -y
  - $D yum install unzip -y
  - $D curl -LO https://github.com/ojdkbuild/praiskup-autotools-epel-6-x86_64/archive/master.zip
  - $D unzip ./master.zip
  - $D yum install -y
            ./praiskup-autotools-epel-6-x86_64-master/autotools-latest-1-25.el6.x86_64.rpm
            ./praiskup-autotools-epel-6-x86_64-master/autotools-latest-autoconf-2.69-11.el6.noarch.rpm
            ./praiskup-autotools-epel-6-x86_64-master/autotools-latest-automake-1.16.1-4.el6.noarch.rpm
            ./praiskup-autotools-epel-6-x86_64-master/autotools-latest-libtool-2.4.6-9.el6.x86_64.rpm
            ./praiskup-autotools-epel-6-x86_64-master/autotools-latest-m4-1.4.18-1.el6.x86_64.rpm
            ./praiskup-autotools-epel-6-x86_64-master/autotools-latest-runtime-1-25.el6.x86_64.rpm
  - $D yum install -y
            centos-release-scl-rh
  - $D yum install -y
            which
            zip
            patch
            alsa-lib-devel
            cups-devel
            freetype-devel
            libX11-devel
            libXi-devel
            libXinerama-devel
            libXt-devel
            libXtst-devel
            libXrandr-devel
            libXrender-devel
            xorg-x11-proto-devel
            elfutils-libelf-devel
            fontconfig-devel
            devtoolset-7
            autotools-latest
  - $D curl -LO https://github.com/ojdkbuild/contrib_jdk14u-ci/releases/download/jdk-14.0.2%2B12/jdk-14.0.2-ojdkbuild-linux-x64.zip
  - $D unzip -q jdk-14.0.2-ojdkbuild-linux-x64.zip
  - $D mv jdk-14.0.2-ojdkbuild-linux-x64 bootjdk

before_script:
  - $D curl -LO http://hg.openjdk.java.net/jdk-updates/jdk15u/archive/${OJDK_TAG}.tar.bz2
  - $D tar -xjf ${OJDK_TAG}.tar.bz2
  - $D rm ${OJDK_TAG}.tar.bz2
  - $D mv jdk15u-${OJDK_TAG} jdk15u

script:
  - $D mkdir jdkbuild
  - $D bash -c "cd jdkbuild &&
        bash /opt/jdk15u/configure
        --disable-warnings-as-errors
        --disable-hotspot-gtest
        --with-native-debug-symbols=${OJDK_WITH_NATIVE_DEBUG_SYMBOLS} 
        --with-debug-level=${OJDK_WITH_DEBUG_LEVEL}
        --with-stdc++lib=static
        --with-zlib=bundled
        --with-boot-jdk=/opt/bootjdk
        --with-version-pre=''
        --with-version-build=${OJDK_BUILD}
        --with-version-opt=''
        --with-vendor-version-string=20.9
        --with-vendor-name=ojdkbuild
        --with-vendor-url=https://github.com/ojdkbuild
        --with-vendor-bug-url=https://github.com/ojdkbuild/ojdkbuild/issues
        --with-vendor-vm-bug-url=https://github.com/ojdkbuild/ojdkbuild/issues
        --with-log=info"
  - $D bash -c "cd jdkbuild && make images"
  - $D mv /opt/jdkbuild/images/jdk ${OJDK_IMAGE}
  - $D rm -rf ./${OJDK_IMAGE}/demo
  - $D zip -qyr9 ${OJDK_IMAGE}.zip ${OJDK_IMAGE}
  - $D mv ${OJDK_IMAGE}.zip /host/
  - sha256sum ${OJDK_IMAGE}.zip > ${OJDK_IMAGE}.zip.sha256

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: mWNb4svbiQi0Lu37E5fVxSb3V1RIWQ5u4FIkLyPbbzl7nbMQ8D7JvS34AQ+MmsGgIRypV14jhe0cbQ9r8SyoHXgiYTYd5kDTLd1NUEmDRlxPDKCS2DEX+YqK6y7QTKOxYVTH1egSSk8namiAH9RMghMkZDMyESiAe1IGafYQlmJk/5kccX3603aksXtQAMZGOr1JweAvxuG9blXubzRgS0CeucEChVn3XuoUQXb9ph3xM+vaskfp/wBuKWjFyMuO6c2tPRNVRHQBqVwQbN8SLwOIO6arDTyKJAhCanYaaLd+CTA9DHa7TFJF9QOoigq2iHWVfHOZMrPvatTTA5RJd8iuDegXrSQ2e9w6KqV1JVfQxatpV9L1l3tQ6LJ0pRWn7/9o73APHiYyBu+m3bs/VmMmGFmLPA2JdHhfAux4EZ4ji0uarGQFInsZlLY5St+iyrmFs7Ydza+yRJyKsxcd1zon9z5q0CpcbGlowSZb0LMoRhWNwLw7SRLT8XX8XrqbDNAHArSJw7d/AVVLc2GIu+PppOa401mLgiVvy4IaIIQm5Jja469ImO1e6tVI1GPdHRq4GEHd6EM/f8WuD++VlRidCJqSiVpK3HCVa1MKHRZt69jfRU8odnZvPkQcwc22CQVaTdrvx5WIn4vkKD2jUjZ1gIARFMfB803/yFrUcKk=
  file:
    - ${OJDK_IMAGE}.zip
    - ${OJDK_IMAGE}.zip.sha256
  on:
    repo: ojdkbuild/contrib_jdk15u-ci
    tags: true

